### ISSUE TITLE
Leverage secret file for authentication

### ISSUE THREAD

**Issue by AlwaySummit** [Lirt/velero-plugin-for-openstack#15]
Hi @Lirt 

I notice that "--no-secret" is used when installing plugin which means the users have to declare all the variables in deployment or daemonset or something like that. It's fine in local but sort of inappropriate in production I suppose. For example, I have to declare these variables below in deployment.yaml to ensure authentication is passed.
![image](https://user-images.githubusercontent.com/20851530/111440522-67db9580-8741-11eb-8aaf-19e35a51ee0c.png)

- **Have you ever considered creating a secret file for authentication?** 
- **Besides, the "openstack" is not yet presented in supported provider lists of velero official doc. Would you like to add openstack into the doc for the convenience of others as well?**
- **Would you like to give me any suggestions on how to deal with those OS variables if no secret file used?**

I suppose there are two parts of modification if using secret file on velero side:

- Add openstack credentials file in pkg/install/daemonset.go and pkg/install/deployment.go. The value should be /credentials/cloud. The aws credentials file is described as below:
```
The cloud-credentials secret exists in the Velero server's namespace

The cloud-credentials secret has a single key, cloud, whose value is the contents of the credentials-velero file

The credentials-velero file is formatted properly and has the correct values:

[default]
aws_access_key_id=<your AWS access key ID>
aws_secret_access_key=<your AWS secret access key>
The cloud-credentials secret is defined as a volume for the Velero deployment

The cloud-credentials secret is being mounted into the Velero server pod at /credentials
```
- Add openstack related information into site/docs/master/supported-providers.md

Nevertheless, it's just my thoughts and I believe I'm not 100% correct obviously because I'm not expert on this part. Could you please share your opinion or recommendation? Thanks.

**Comment by Lirt** [comment]
Hello,

regarding the secret, Kubernetes can safely inject environment variables. You need to create secret with variables specified as you did and load it using `envFrom`.

So if you run `kubectl explain deployment.spec.template.spec.containers.envFrom` you can see documentation about it.

In the yaml it looks like this (I can give you full example later when I have time):

```yaml
       containers:
       - name: my-container
         envFrom:
         - secretRef:
             name: my-swift-secret
```

**Comment by Lirt** [comment]
I personally install velero and also the plugin using helm chart https://github.com/vmware-tanzu/helm-charts/tree/main/charts/velero.

I can give you full example if you want or include it in documentation. Maybe it would be useful for everyone.

**Comment by Lirt** [comment]
Regarding using file as an authentication, gophercloud as library offered only authenticating using environment variables or reading RC file. Now I found out that there is also function in `utils` (different library) to read credentials from file in `clouds.yaml` format.

I can implement this, but in the end you will create the secret file in a simliar kubernetes way as I described above:
1. Create secret with clouds.yaml contents.
2. Create volume of type secret referring to the secret.
3. VolumeMount it to the plugin container.

So I think there is no security benefit from it.

**Comment by Lirt** [comment]
Here is `values.yaml` file I use when installing from [helm chart](https://github.com/vmware-tanzu/helm-charts/tree/main/charts/velero). Setting `credentials.extraSecretRef` to secret `velero-credentials` makes it to load it. The secret must be created beforehand of course and it is up to you how to install it (gitops, flux, argocd, vault, manually).

```yaml
---
deployRestic: false
serviceAccount:
  server:
    create: true
    name: velero
credentials:
  extraSecretRef: "velero-credentials"
configuration:
  provider: swift
  backupStorageLocation:
    bucket: "velero-backup-for-my-cluster"
schedules:
  caas-full-backup:
    schedule: '0 * * * *'
    template:
      excludedNamespaces: null
      excludedResources: null
      hooks:
        resources: null
      includeClusterResources: null
      includedNamespaces:
      - '*'
      includedResources: null
      labelSelector: null
      storageLocation: ""
      ttl: 168h0m0s
metrics:
  serviceMonitor:
    enabled: false
initContainers:
- name: velero-plugin-swift
  image: lirt/velero-plugin-swift:v0.1.1
  imagePullPolicy: IfNotPresent
  volumeMounts:
  - mountPath: /target
    name: plugins
snapshotsEnabled: false
backupsEnabled: true
```

**Comment by Lirt** [comment]
Regarding making plugin community official I was interested but I need to improve quality control -> implement more tests and prepare local dev environment (still WIP).

**Comment by AlwaySummit** [comment]
Hi @Lirt 

Thanks for your time on this. Basically, I'm doing as exaclty what you just mentioned. Here is my partial values.yaml and I'm going to set all the credentials to the **secretContents** value via **envFrom**.
```
credentials:
  useSecret: true
  secretContents: {}

# Whether to create backupstoragelocation crd, if false => do not create a default backup location
backupsEnabled: true
# Whether to create volumesnapshotlocation crd, if false => disable snapshot feature
snapshotsEnabled: false
```

Here is my partial secret.yaml. Actually, I'm working on the multi cloud and basically I don't intend to change the format of secret file. The question is if I use envFrom to load the secret, the variables in OS are going to be like "cloud: OS_AUTH_URL=xx, OS_USERNAME=xx" and it is definitely can't be recognized by velero. Is there any approach to load the value of cloud only instead of the whole data content? I'm not sure if I make myself clear, If not, sorry for my weak expression and knowledge and feel free ask me anytime.
```
apiVersion: v1
data:
  cloud: **
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"cloud":"**"},"kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"velero","name":"velero","namespace":"default"},"type":"Opaque"}
  creationTimestamp: "2021-01-14T05:41:20Z"
  labels:
    app.kubernetes.io/name: velero
  name: velero
  namespace: default
type: Opaque
```

BTW, It is how I use envFrom to load secret.
```

{{- if eq $provider "swift" }}
          envFrom:
            - secretRef:
                name: velero
```

**Comment by Lirt** [comment]
Kubernetes doesn't have function for extracting specific content from file/secret as far as I know.

I think you need to extract the cloud part you want for each cloud (for example if you have multiple Swifts and you want to use the one in that cloud) and put it into separate secret (that's not a big issue to have one more secret). If you only use one Swift, just extract its cloud part and create that secret for velero.

If there was functionality like this with multi-cloud `clouds.yaml` file the plugin would also need to know which one of those clouds does user want to use for the backup. So there would need to be additional variable and logic.

I think Velero cannot benefit from having multiple clouds in its config. There is always only one place where to store the cluster backups or snapshots (it's designed like that). Also for snapshots it is technically impossible, because you always must do snapshot of volume in the same locality as where the volume is.

**Comment by AlwaySummit** [comment]
Okay. Currently, we have aws, azure providers, etc. And they retrieve credentials from /credentials/cloud. Perhaps I need reform the structure of secret.yaml to adapt with swift. Thanks anyway and I'll close this ticket. Appreciate it.

**Comment by Lirt** [comment]
Ah you mean multiple environment setup. I misunderstood a bit. I can include auth via file later on but the priority is now for block storage implementation. Hope you will find solution for now.

**Comment by AlwaySummit** [comment]
Hi @Lirt 

Sorry for not making myself clear. There are indeed multiple cloud environment from my side. Besides, I'd like to ask what do you mean by including auth via file? You mean you're going to use /credentials/cloud as well instead of loading OS variables in deployment by our own? If so, I'll make a workaround for this for now and adapt the new code in the future. Obviously, block storage is prior for now and I hope you can make further progress on this. Thanks again.

**Comment by Lirt** [comment]
Yes, to look for cloud config using standard openstack and velreo paths or custom path. 

The block storage support was released today.

**Comment by AlwaySummit** [comment]
That's awesome! Thanks.

**Comment by AlwaySummit** [comment]
Hi @Lirt ,

Sorry to trouble you again. I'd like to confirm if the plugin supports retrieving secrets from /credentials/cloud. Based on aforementioned circumstance, I'm enabling multi-environment setup and looking for a uniform pattern to retrieve secrets from  /credentials/cloud. Thanks.
BTW, I'd like to give you an sample of deployment.yaml for your reference.
```
env:
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: LD_LIBRARY_PATH
              value: /plugins
          {{- if .Values.credentials.useSecret }}
            {{- if eq $provider "aws" }}
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
            {{- else if eq $provider "azure" }}
            - name: AZURE_CREDENTIALS_FILE
              value: /credentials/cloud
            {{- else if eq $provider "alibabacloud" }}
            - name: ALIBABA_CLOUD_CREDENTIALS_FILE
              value: /credentials/cloud
            {{- else if eq $provider "openstack" }}
            - name: OPENSTACK_CREDENTIALS_FILE
              value: /credentials/cloud
            {{- end }}
          {{- end }}
```
