### ISSUE TITLE
failed to create cinder storage client

### ISSUE THREAD

**Issue by edo3** [Lirt/velero-plugin-for-openstack#24]
Hi.

I'm currently on OVH cloud and want to create snapshots for my PVCs. 

I'm facing the following errors
```
time="2021-05-06T15:15:02Z" level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/platform-backup-3 error="rpc error: code = Unknown desc = failed to create cinder storage client: No suitable endpoint could be found in the service catalog." logSource="pkg/backup/item_backupper.go:449" name=ovh-managed-kubernetes-u359ha-pvc-14db48b5-590d-4119-a063-c64832cc7231 namespace= persistentVolume=ovh-managed-kubernetes-u359ha-pvc-14db48b5-590d-4119-a063-c64832cc7231 resource=persistentvolumes volumeSnapshotLocation=default
time="2021-05-06T15:25:03Z" level=error msg="Timed out awaiting reconciliation of volumesnapshot platform-production/velero-mysql-claim-lcck5" backup=velero/platform-backup-3 cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:188" pluginName=velero-plugin-for-csi
time="2021-05-06T15:25:03Z" level=info msg="1 errors encountered backup up item" backup=velero/platform-backup-3 logSource="pkg/backup/backup.go:427" name=db-544987c5f7-nv777
time="2021-05-06T15:25:03Z" level=error msg="Error backing up item" backup=velero/platform-backup-3 error="error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=platform-production, name=velero-mysql-claim-lcck5): rpc error: code = Unknown desc = timed out waiting for the condition" logSource="pkg/backup/backup.go:431" name=db-544987c5f7-nv777
```

I have the following volume snapshotclass:
```
  apiVersion: snapshot.storage.k8s.io/v1beta1
  deletionPolicy: Retain
  driver: cinder.csi.openstack.org
  kind: VolumeSnapshotClass
  metadata:
      labels:
      velero.io/csi-volumesnapshot-class: "true"
    name: csi-cinder-snapclass
```

and the following StorageClass:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  managedFields:
  - apiVersion: storage.k8s.io/v1
    operation: Update
  name: csi-cinder-high-speed
parameters:
  availability: nova
  type: high-speed
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
