### ISSUE TITLE
Velero with restic doesn't create a volume in Openstack during restore

### ISSUE THREAD

**Issue by nvpuri** [Lirt/velero-plugin-for-openstack#46]
Hello,

To test out velero's backup and restore features with restic, I am trying to restore EFK stack from Azure AKS. I have an EFK stack setup and running in Azure. I installed velero with restic in Azure using helm charts and [azure plugin](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure) and tested out velero backup and restore features in Azure and verified that it worked.

Now, we have to deal with multiple cloud providers and we decided to take backups in Azure and restore them to Openstack (in this case) instead of taking backups in each cloud provider for obvious reasons. I made modifications to my helm installation to the OpenStack cloud as per the values.yaml file

```yaml

credentials:
  extraSecretRef: "velero-credentials"
configuration:
  provider: azure
#backupstoragelocation of azure
  backupStorageLocation:
    name: default
    bucket: velero
    #bucket: test
    provider: velero.io/azure
    config:
      resourceGroup: resourcegroup
      storageAccount: storageaccount
      subscriptionId: SID
  volumeSnapshotLocation:
    name: azure-default
    provider: velero.io/azure
initContainers:
  - name: velero-plugin-openstack
    image: lirt/velero-plugin-for-openstack:v0.3.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-microsoft-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.5.0
    volumeMounts:
      - mountPath: /target
        name: plugins
snapshotsEnabled: true
backupsEnabled: true
deployRestic: true

```
The velero namespace and credentials were created before running the velero installation command in Openstack. The credentials file has all the Openstack variables with values in b64 format. After installation, running

`velero backup get`

in my OS tenant, gives me the backups I created in Azure which is fine.

But when I restore, I see the PV that is created in Azure restored to OpenStack but a new volume is not created in OpenStack. 

The parameters of the restored PV in OS are:

```yaml

 csi:
    driver: disk.csi.azure.com
    volumeHandle: >-
      /subscriptions/SID/resourceGroups/REesourceGroup/providers/Microsoft.Compute/disks/restore-xxxxx
    volumeAttributes:
      csi.storage.k8s.io/pv/name: pvc-xxxx-yyyy
      csi.storage.k8s.io/pvc/name: elastic-data-elasticsearch-0

```

instead of something like

```yaml

csi:
    driver: cinder.csi.openstack.org
    volumeHandle: VH
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: xxxx-yyy-cinder.csi.openstack.org

```

I have also added the configmap files that can change the storage classes from backup to restore mentioned [here](https://velero.io/docs/v1.9/restore-reference/#changing-pvpvc-storage-classes) before running the restore.

I am pretty sure I've overlooked something in order to get this idea working but if not, can you suggest a workaround for this?

**Comment by Lirt** [comment]
Hi @nvpuri,

In this scenario where you need to restore volume from different cloud provider the job should be in my opinion done mainly by `restic`. I think that in this case you actually don't even need Openstack plugin for Velero. 

The volume snapshot functionality cannot work between cloud providers. It's job is to create snapshot from volume in one specific region of one cloud provider. This snapshot is not possible to be restored in other cloud providers. It's a snapshot object specific to a cloud and storage backend, so I can't think of a way it could be done.

So in your case you should mostly rely on restic to backup/restore the data to/from object storage. First check if `restic` backs-up volumes you want (remember to use annotation as mentioned in [docs](https://velero.io/docs/main/restic/#using-opt-in-pod-volume-backup)). Then in your Openstack you should use only Azure plugin (to use same object storage where restic backups are stored) and run restore.

I also think you should either not use `snapshotsEnabled: true` at all or use `--restore-volumes=false` in `velero restore` command to not try to create the PVs/PVCs by cloud provider. Then `restic` should take care of rest.

To check if restic works you can run backup and then check if you have any `podvolumebackups` CRs and check their config. Then after you run restore you should see `podvolumerestores` CRs - they will spawn a pod and this pod will have PVC with some kind of `StorageClass` and CSI controller should take care of creating new PV.

You can try it - see error logs and let me know if it helps. If it doesn't help I will need some time to test this scenario.

**Comment by nvpuri** [comment]
Hi @Lirt,

> So in your case you should mostly rely on restic to backup/restore the data to/from object storage. First check if restic backs-up volumes you want (remember to use annotation as mentioned in [docs](https://velero.io/docs/main/restic/#using-opt-in-pod-volume-backup)). Then in your Openstack you should use only Azure plugin (to use same object storage where restic backups are stored) and run restore.

Yes, I was using velero with restic for this backup and restore to work. Restic is backing up volumes in Azure. I created annotations for the pods that need backing up. After running,

`velero backup create logging-backup --include-namespaces logging`

 I was able to see that Backup and PodVolumeBackup CRDs were created in Azure.
 
 In my Openstack, I removed the OS plugin and used only Azure plugin while installing Velero. I also excluded the `snapshotsEnabled: true` option while installing. I was able to see the same `logging` CRDs (both in Backup and PodVolumeBackup) in OS tenant.
 
 But while running `restore`, the issue was the same. The pods come up but no volume is created in OS. A PVC is created but the storage class shown is Azure's and no OS's. I added the configmap that is mentioned [here](https://velero.io/docs/v1.9/restore-reference/#changing-pvpvc-storage-classes) and when I restart I don't even see the pods come up. 
 
 There are no logs from `velero restore logs logging`
 
> Logs for restore "logging" are not available until it's finished processing. Please wait until the restore has a phase of Completed or Failed and try again

And `velero restore describe logging`
is stuck on `Phase:  New`

The results are the same when I add the `--restore-volumes=false` flag to the restore command. i.e. before adding the configmap, no new volumes are created and after adding the configmap, the restored pods don't even come up.

And it's empty on `podvolumerestores` all the time but I see `podVolumeBackup` has the backup CRs. 

Velero restic logs in Openstack:

```
time="2022-10-31T06:40:49Z" level=info msg="Starting Velero restic server v1.9.2 (82a100981cc66d119cf9b1d121f45c5c9dcf99e1-dirty)" logSource="pkg/cmd/cli/restic/server.go:87"
time="2022-10-31T06:40:49Z" level=info msg="Setting log-level to INFO"
2022-10-31T06:40:49.277Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
time="2022-10-31T06:40:49Z" level=info msg="Starting metric server for restic at address [:8085]" logSource="pkg/cmd/cli/restic/server.go:177"
time="2022-10-31T06:40:49Z" level=info msg="Starting controllers" logSource="pkg/cmd/cli/restic/server.go:188"
time="2022-10-31T06:40:49Z" level=info msg="Controllers starting..." logSource="pkg/cmd/cli/restic/server.go:219"
2022-10-31T06:40:49.337Z	INFO	starting metrics server	{"path": "/metrics"}
2022-10-31T06:40:49.338Z	INFO	controller.podvolumebackup	Starting EventSource	{"reconciler group": "velero.io", "reconciler kind": "PodVolumeBackup", "source": "kind source: /, Kind="}
2022-10-31T06:40:49.338Z	INFO	controller.podvolumebackup	Starting Controller	{"reconciler group": "velero.io", "reconciler kind": "PodVolumeBackup"}
2022-10-31T06:40:49.338Z	INFO	controller.podvolumerestore	Starting EventSource	{"reconciler group": "velero.io", "reconciler kind": "PodVolumeRestore", "source": "kind source: /, Kind="}
2022-10-31T06:40:49.338Z	INFO	controller.podvolumerestore	Starting EventSource	{"reconciler group": "velero.io", "reconciler kind": "PodVolumeRestore", "source": "kind source: /, Kind="}
2022-10-31T06:40:49.338Z	INFO	controller.podvolumerestore	Starting Controller	{"reconciler group": "velero.io", "reconciler kind": "PodVolumeRestore"}
2022-10-31T06:40:49.439Z	INFO	controller.podvolumebackup	Starting workers	{"reconciler group": "velero.io", "reconciler kind": "PodVolumeBackup", "worker count": 1}
2022-10-31T06:40:49.439Z	INFO	controller.podvolumerestore	Starting workers	{"reconciler group": "velero.io", "reconciler kind": "PodVolumeRestore", "worker count": 1}
time="2022-10-31T06:41:09Z" level=info msg="PodVolumeBackup starting" backup=velero/logging controller=podvolumebackup logSource="pkg/controller/pod_volume_backup_controller.go:87" podvolumebackup=velero/logging-vd6bg
time="2022-10-31T06:51:07Z" level=warning msg="PodVolumeRestore not found, skip" PodVolumeRestore=velero/logging-kt7mv controller=PodVolumeRestore logSource="pkg/controller/pod_volume_restore_controller.go:78"
```

Please let me know if there's anything else I have to try. Thanks for yo9ur help!

**Comment by Lirt** [comment]
Then I think the issue is outside of this plugin. 

Maybe something is wrong in the ConfigMap you mentioned (https://velero.io/docs/main/restore-reference/#changing-pvpvc-storage-classes). The storage class must be changed after restore to one that exist in Openstack cluster. Then PV will be created and pods will start. The restore will hang until the PVCs are finished.

This part of the configmap must match storage classes that will be renamed (azure->openstack):
```yaml
data:
  # add 1+ key-value pairs here, where the key is the old
  # storage class name and the value is the new storage
  # class name.
  <old-storage-class>: <new-storage-class>
```

If nothing helps you probably need to ask in Velero slack or open issue in their Github :shrug:.

**Comment by nvpuri** [comment]
> The storage class must be changed after restore to one that exist in Openstack cluster.

I applied the configmap before the restore command earlier but now I applied it after the restore command, like you said. I don't think the configmap took affect after applying it after `velero restore`

When I do `velero restore` before applying the configmap, I am able to see an object created in PodVolumeRestore, but there is no spawning of any pod. So no question of that said pod having a storage class in them.

This is the configmap I applied.

```yaml

apiVersion: v1
kind: ConfigMap
metadata:
  # any name can be used; Velero uses the labels (below)
  # to identify it rather than the name
  name: change-storage-class-config
  # must be in the velero namespace
  namespace: velero
  # the below labels should be used verbatim in your
  # ConfigMap.
  labels:
    # this value-less label identifies the ConfigMap as
    # config for a plugin (i.e. the built-in restore item action plugin)
    velero.io/plugin-config: ""
    # this label identifies the name and kind of plugin
    # that this ConfigMap is for.
    velero.io/change-storage-class: RestoreItemAction
data:
  # add 1+ key-value pairs here, where the key is the old
  # storage class name and the value is the new storage
  # class name.
  default: 8k

```
where `default` is the storage class of azure and `8k` is the OS storage class
